containers/podman-py

LICENSE
README.md
connection.py
images/__init__.py
images/images.py
libpod_errors/__init__.py
libpod_errors/errors.py
libpod_errors/utils.py
setup.py

basic layout of the binding framework including errors.  no test has been defined yet.

initial check'in

---

.cirrus.yml
contrib/cirrus/gating/Dockerfile

add cirrus and first shot at gating

---

bors.toml

change approvers thingy to 0

---

.cirrus.yml
Makefile

add target for `make validate` which runs make lint and git-validation

add git-validation

---

.cirrus.yml

Cirrus: Minor image update

---

.gitignore
README.md
podman/images/__init__.py
podman/system/__init__.py

Update .gitignore
Update main readme (fix example)
Add functions:
----System: get_info, show_disk_usage
----Images: image_exists

Fix README and add a few functions

---

.cirrus.yml

Cirrus: Remove unused VM capability

---

podman/images/__init__.py
podman/tests/unit/images/test_images.py

Add a call to allow for image tagging and an example of what is expected for POST data.

Add additional image calls

---

.readthedocs.yaml
docs/index.md

I think this might be enough for now regarding docs. The project structure is pretty intuitive so I just want to give hints. If it gets more complex down the road we have a nice foundation to build upon (and also still enough flexibility to switch to another solution if needed, agile ftw).
Demo view is here: https://eb-podman-py.readthedocs.io/en/latest/

Docs: Covering the Essentials

---

podman/api_connection.py
podman/system/__init__.py

The purpose of this PR is improve the code quality. At this time I used [black](https://github.com/psf/black) as code formatter, keeping the maximum length of the line as 79.
Just 4 files were modified:
* podman/api_connection.py
* podman/system/__ init __.py
* podman/images/__ init __.py
* podman/errors/__ init __.py

Typos style

---

.pylintrc
docs/index.md
podman/pods/__init__.py
podman/tests/unit/pods/test_pods.py

Implementation for pods and disabling too many methods lint rule because
the tests trigger on them.

Initial pods implementation

---

podman/errors/__init__.py
podman/manifests/__init__.py
podman/tests/unit/manifests/test_manifests.py

Initial implementation of the manifest calls.

Implement manifests calls

---

podman/containers/__init__.py
podman/tests/unit/containers/test_containers.py

This change adds additional calls for the other container related calls.
Signed-off-by: Alex Schultz <aschultz@redhat.com>

Additional container calls implementation

---

.gitignore
Makefile
contrib/cirrus/gating/Dockerfile
podman/__init__.py
podman/api/client.py
podman/api/ssh.py
podman/api/uds.py
podman/client.py
podman/domain/containers.py
podman/domain/events.py
podman/domain/images.py
podman/domain/manager.py
podman/domain/networks.py
podman/domain/pods.py
podman/domain/system.py
podman/domain/volumes.py
podman/errors/__init__.py
podman/errors/exceptions.py
podman/tests/unit/test_containers.py
podman/tests/unit/test_podmanclient.py
podman/tlsconfig.py

Introduces the library framework for building a compatible higher level
PodmanClient().
New classes introduced in client.py and domain library.
See, podman/tests/unit/test_podmanclient.py and
podman/tests/unit/test_containers.py.
See also, https://docker-py.readthedocs.io/en/stable/index.html
Pods are handled by mimicking classes and methods of the other areas of
concern.

Framework for compatible PodmanClient

---

podman/api/__init__.py
podman/api/client.py
podman/api/parse_utils.py
podman/client.py
podman/domain/containers.py
podman/domain/containers_manager.py
podman/domain/image_build.py
podman/domain/images_manager.py
podman/domain/system.py
podman/tests/unit/test_containers.py
podman/tests/unit/test_containersmanager.py
podman/tests/unit/test_image.py
podman/tests/unit/test_system.py

PodmanPy Containers and system areas of concern
* Implement most containers and system calls
* Pylint run on all new code
* Updates to code and unittests

PodmanPy Containers and system areas of concern

---

podman/api/__init__.py
podman/api/client.py
podman/api/parse_utils.py
podman/api/url_utils.py
podman/api_connection.py
podman/client.py
podman/domain/containers.py
podman/domain/containers_manager.py
podman/domain/images_manager.py
podman/domain/ipam.py
podman/domain/manager.py
podman/domain/networks.py
podman/domain/networks_manager.py
podman/domain/pods.py
podman/domain/volumes.py
podman/tests/unit/test_containers.py
podman/tests/unit/test_network.py
podman/tests/unit/test_networksmanager.py
podman/tests/unit/test_podsmanager.py

* Implement network and network manager classes/methods
* Start volumes and pods
* Pylint run on all new code
* Updates to code and unittests

PodmanPy Network area of concern

---

podman/client.py
podman/domain/networks.py
podman/domain/networks_manager.py
podman/domain/volumes.py
podman/errors/exceptions.py
podman/tests/unit/test_network.py
podman/tests/unit/test_volume.py
podman/tests/unit/test_volumesmanager.py

* Bindings for Volume and VolumesManager
* unittests
* pylint

PythonPy Volumes

---

podman/networks/__init__.py
podman/tests/unit/networks/test_networks.py

Adding one missing method with ut, skipped filters as they are not implemented yet in podman

prune networks method with tests and typo fixes

---

podman/client.py
podman/domain/containers.py
podman/domain/networks_manager.py
podman/domain/pods.py
podman/domain/pods_manager.py
podman/tests/unit/test_pod.py
podman/tests/unit/test_podsmanager.py

* Pod operations and classes modeled after the Container operations
* unittests provided
* pylint coverage

PodmanPy Pod Operations

---

.cirrus.yml
contrib/cirrus/latest_podman.sh

Need the latest podman from master to enable the co-development between
the two repositories.

Build podman from master for testing

---

.cirrus.yml
.pylintrc
contrib/cirrus/latest_podman.sh
contrib/cirrus/test.sh
podman/api/__init__.py
podman/api/parse_utils.py
podman/api/tar_utils.py
podman/api/uds.py
podman/client.py
podman/domain/containers.py
podman/domain/containers_create.py
podman/domain/containers_manager.py
podman/domain/containers_run.py
podman/domain/events.py
podman/domain/images.py
podman/domain/images_build.py
podman/domain/images_manager.py
podman/domain/ipam.py
podman/domain/manager.py
podman/domain/networks.py
podman/domain/networks_manager.py
podman/domain/pods.py
podman/domain/pods_manager.py
podman/domain/registry_data.py
podman/domain/system.py
podman/domain/volumes.py
podman/tests/integration/test_containers.py
podman/tests/integration/utils.py
podman/tests/unit/test_containersmanager.py
podman/tests/unit/test_volumesmanager.py

Finish Containers tests and implementations
* Add helper methods for streaming frames
* Generalized creating tar files
* Tweaked dict() scrubber to walk all container types
* Container Prune
* Container Run
Depends on https://github.com/containers/podman/pull/9892

Finish Containers tests and implementations

---

podman/client.py
podman/domain/images.py
podman/domain/images_manager.py
podman/domain/manifests.py
podman/tests/integration/test_images.py
podman/tests/integration/test_manifests.py
podman/tests/unit/test_image.py
podman/tests/unit/test_manifests.py

* New code for working with manifests stored by a Podman service
* Add unit and integration tests
* Update image files as needed

Implement Manifest and ManifestsManager

---

podman/api/http_utils.py
podman/domain/containers_create.py
podman/domain/containers_manager.py
podman/domain/manager.py
podman/domain/pods.py
podman/domain/pods_manager.py
podman/domain/volumes.py
podman/tests/integration/test_containers.py
podman/tests/integration/test_pods.py
podman/tests/unit/test_manager.py
podman/tests/unit/test_pod.py
podman/tests/unit/test_podsmanager.py

Implement Pod python bindings and tests

---

README.md
podman/api/http_utils.py
podman/client.py
podman/domain/pods_manager.py
podman/domain/secrets.py
podman/tests/integration/test_images.py
podman/tests/integration/test_secrets.py
podman/tests/unit/test_podmanclient.py
podman/tests/unit/test_secrets.py

* Implement secrets binding and tests
* Add contextmanager protocol to PodmanClient

Implement secrets bindings

---

.cirrus.yml
contrib/cirrus/test.sh

Update to F34beta VM images

---

podman/domain/networks.py
podman/tests/integration/test_networks.py

* Fixed tests to not trigger CNI issue with supernetting

Unskip Network integration tests

---

README.md
docs/source/conf.py
docs/source/index.rst
podman/api/__init__.py
podman/api/ssh.py
podman/api/uds.py
podman/client.py
podman/domain/containers_create.py
podman/domain/images_manager.py
podman/domain/manifests.py
podman/domain/networks_manager.py
podman/domain/pods_manager.py
podman/domain/volumes.py
podman/errors/__init__.py
podman/errors/exceptions.py
podman/tlsconfig.py
requirements.txt

* Add docs target to Makefile
* Started updating some docstrings
* Added support for connections from containers.conf
* Ported more uses of XDG_* envvar to xdg package
* Downgrade modules in requirements.txt as needed by RHEL/Fedora
packaging.

Introduce sphinx processing for html API web site

---

podman/api/version.py

Bump version to fix release on github

---

README.md

Rename default branch main

---

docs/source/conf.py
podman/api/version.py

Need bump for changes in dependency version checking

Bump version for tagging release

---

CONTRIBUTING.md

Update IRC monitored network

---

podman/domain/containers_create.py

https://github.com/containers/podman-py/issues/118

Change working_dir to work_dir in create_container

---

Makefile
podman/api/__init__.py
podman/api/typing_extensions.py
podman/domain/containers_create.py
setup.cfg

Workaround typing_extensions module requirement

---

podman/tests/__init__.py
podman/version.py

Bump version and publish release

---

podman/__init__.py
podman/api/__init__.py
podman/api/client.py
podman/api/ssh.py
podman/api/typing_extensions.py
podman/tests/integration/base.py
podman/tests/integration/test_adapters.py
podman/tests/integration/test_manifests.py
podman/tests/integration/test_pods.py
podman/tests/integration/test_system.py
podman/tests/integration/utils.py
podman/tests/unit/test_api_utils.py
podman/tests/unit/test_build.py
podman/tests/unit/test_container.py
podman/tests/unit/test_containersmanager.py
podman/tests/unit/test_image.py
podman/tests/unit/test_imagesmanager.py
podman/tests/unit/test_pod.py
podman/tests/unit/test_podsmanager.py
podman/tests/unit/test_registrydata.py
podman/tests/unit/test_system.py
pyproject.toml

- Run black against whole project
- with new string processing turned on
- Cleaned up imports as well

Cleanup code and CI

---

.readthedocs.yaml
docs/source/conf.py

* Update the URLs for external links to https
* Improve configuration for readthedocs

Update Sphinx configuration

---

podman/domain/containers.py

Pull container name from list of Names
Fixed CI check for Name.

Fix container name property

---

.cirrus.yml
.github/workflows/pr.yml

* Update VM images
* Replace use of gitvalidation tool

Cirrus: Update Fedora + Ubuntu CI VMs

---

podman/api/client.py
podman/domain/containers.py
podman/domain/images_manager.py
podman/domain/manager.py
podman/tests/integration/test_images.py
pyproject.toml

* Present service progress to caller when using Build().
* Update changed black options
Closes #171

Build progress via Generator

---

CONTRIBUTING.md

Add docstring clarification

---

podman/domain/images_manager.py

I'm getting `unauthorized` from quay.io with `credentials` path param. Use `X-Registry-Auth` instead.

Use X-Registry-Auth header for pull

---

.cirrus.yml

Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>
@jwhonce @rhatdan @cevich PTAL

Cirrus: Bump to Fedora 36 and Ubuntu 22.04 LTS

---

podman/domain/containers.py

This change adds a basic implementation of exec_run for containers
Environment variable conversions are handled from dict->list[str]
DetachKeys will need an actual argument option
detach, stream, socket, and demux arguments are currently not handled.

Add exec_run implementation for containers

---

Makefile
tox.ini

Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>
@cdoern @jwhonce PTAL

tox: test with python 3.11

---

Makefile
podman/tests/__init__.py
podman/version.py

Bump to version 4.2.0

---

podman/domain/containers.py
podman/tests/unit/test_container.py

Support passing of interval and condition in podman wait calls

---

setup.cfg

Update supported Python versions

---

Makefile
podman/version.py

bumping version numbers to v4.0.1, tag to come soon

bump to v4.0.1

---

Makefile
podman/tests/__init__.py
podman/version.py

bump to v4.2.1

---

.readthedocs.yaml
docs/source/index.rst

work through errors from folks and alter build process for api doc

enable readthedoc builds

---

.cirrus.yml
.pylintrc
podman/api/typing_extensions.py
podman/domain/images_manager.py
podman/domain/manager.py
podman/domain/networks.py
podman/domain/secrets.py
podman/domain/volumes.py

Update files to adhere to new lint requirements

---

podman/domain/containers_create.py

Signed-off-by: Tim Carpenter <timc@users.noreply.github.com>

Correctly add secrets to container on creation

---

Makefile
podman/tests/__init__.py
podman/version.py

Includes patch to revert the toml library

Bump version to 4.4.1

---

CONTRIBUTING.md

Fixed the merge bot to auto merge once the tests pass, testing that as well.

Minor text fixes in contributing.md

---

.github/renovate.json5

I think maybe @rhatdan is busy with lots of other things, let's reduce his burden a little.

Swap renovate dep. update. PR assignments

---

.readthedocs.yaml
Makefile
docs/source/conf.py

Major issue is readthedocs has fixed paths
Replaces https://github.com/containers/podman-py/pull/221

Update Makefile to emulate readthedocs automation

---

podman/api/ssh.py
podman/api/uds.py
requirements.txt
setup.cfg
test-requirements.txt

This is required for compatibillity with urllib3 2.0+
Fixes: #281,#287

Switch HTTPConnection from http.client to urllib3.connection

---

rpm/python-podman.spec

Remove unnecessary dependencies and conditionals
Dist-git ref for dependency update:
https://src.fedoraproject.org/rpms/python-podman/pull-request/2
From: Yaakov Selkowitz <yselkowi@redhat.com>

[CI:BUILD] RPM: Cleanup

---

Makefile
podman/version.py
setup.cfg

And then bump version to 4.7.0

Bump version to 4.7.0

---

setup.cfg

Fixes https://github.com/containers/podman-py/issues/352

Add rich dep to setup.cfg

---

Makefile
podman/version.py
setup.cfg

Bump version to 5.0.0 for the 5.0 release

Bump version to 5.0.0

---

Makefile
podman/tests/__init__.py
podman/version.py
setup.cfg

Also adding myself to Authors in setup.cfg

Bump version to 5.2.0

---

podman/domain/containers_run.py

Fixes: https://github.com/containers/podman-py/issues/425

Remove wait condition in run()

---

OWNERS

Remove duplicate reviewers (from approvers) and promote Nicola to approver.  Minor changes to both reviewers and approvers

Audit and Update OWNERS file

---

podman/api/__init__.py
podman/api/api_versions.py
podman/api/client.py

This PR fixes a cyclic import detected by Pylint.

Fix cyclic-import

---

.cirrus.yml
podman/api/client.py
podman/api/ssh.py
podman/api/typing_extensions.py
podman/api/uds.py
podman/client.py
podman/domain/containers.py
podman/domain/containers_create.py
podman/domain/containers_run.py
podman/domain/images_manager.py
podman/domain/ipam.py
podman/domain/system.py
podman/errors/exceptions.py
podman/tests/integration/test_container_create.py
podman/tests/integration/utils.py
podman/tests/unit/test_build.py
podman/tests/unit/test_config.py
podman/tests/unit/test_container.py
podman/tests/unit/test_containersmanager.py
podman/tests/unit/test_events.py
podman/tests/unit/test_image.py
podman/tests/unit/test_imagesmanager.py
podman/tests/unit/test_network.py
podman/tests/unit/test_networksmanager.py
podman/tests/unit/test_pod.py
podman/tests/unit/test_podmanclient.py
podman/tests/unit/test_podsmanager.py

This PR backports fixes a typo in dns_option and adds a DNS option container creation test to version 4.6.
Fixes: https://issues.redhat.com/browse/RHEL-31069

[release-4.9] Fix dns_option typo and add test of container create with DNS option

---

podman/api/output_utils.py
podman/api/parse_utils.py
podman/domain/containers.py
podman/tests/integration/test_container_exec.py

Added support for streaming output in Container.exec_run(). Streaming functionality should support demuxed output if specified. Return format should match docker's python library.

Added stream support to Container.exec_run().

---

docs/source/index.rst

fix[docs]: Unindented example code on the index page

---

README.md

docs: Add Installation and docs in README.md

---

Makefile
podman/tests/__init__.py
podman/version.py
pyproject.toml
setup.cfg
tox.ini

Fixes tests in https://github.com/containers/podman-py/pull/468

Bump release to 5.3.0 and drop python<3.8

---

OWNERS

Adding additional reviewer to Owners file.

Add edward5hen as reviewer

---

podman/api/parse_utils.py
podman/domain/images_manager.py
podman/tests/unit/test_parse_utils.py

Fixes: https://issues.redhat.com/browse/RUN-2313

Honor port numbers in urls for image.pull

---

.packit.yaml
Makefile
plans/main.fmf
pyproject.toml
tests/main.fmf

depends on https://github.com/containers/podman-py/pull/480
cc: @lsm5

Add upstream tests to tmt

---

pyproject.toml

pyproject toml fixed for podman submodules invisibility

---

.packit.yaml
.pre-commit-config.yaml
gating.yml
plans/main.fmf
tests/main.fmf

Cross referencing https://src.fedoraproject.org/rpms/python-podman/pull-request/40
@lsm5 PTAL

Enable tmt downstream

---

podman/domain/volumes.py
podman/tests/unit/test_volume.py

Add inspect volume

---

podman/domain/images_manager.py

Fixes: #523 
> The push function has a stream parameter.
> But it seems that the http post request is not streaming.
Related code for Docker:
https://github.com/docker/docker-py/blob/db7f8b8bb67e485a7192846906f600a52e0aa623/docker/api/image.py#L491-L493

fix: push image does not stream

---

.pre-commit-config.yaml
Makefile
podman/api/cached_property.py
podman/api/http_utils.py
podman/api/parse_utils.py
podman/domain/containers_manager.py
podman/domain/images.py
podman/domain/networks_manager.py
podman/domain/pods.py
podman/errors/__init__.py
podman/tests/integration/utils.py
podman/tests/unit/test_api_utils.py
podman/tests/unit/test_parse_utils.py
pyproject.toml
tox.ini

Follow up to: #294 
Related to: #293 
I think that type checking helps to avoid errors and bugs.
In #294 you can see how extensive the topic is and cannot be realised with one PR. Therefore the attempt to make it incremental.
Here pipeline, configuration and a few fixes, so that it becomes transparent which files still need to be fixed in the future.

misc: add mypy for type checking

---

podman/domain/images_build.py
podman/tests/integration/test_images.py

A "context", as pertaining to image builds, is a Dockerfile/Containerfile plus all local files that can be referenced via commands such as COPY, etc, in the Dockerfile.  The context is typically serialized as a tarball.
Podman-py's `build()` method already offers a couple of convenient ways to automatically construct this serialized tarball.
This PR adds the ability to directly pass in an already-constructed context tarball.  This addresses #551 .

Add support for custom contexts

---

podman/tests/integration/test_container_create.py
podman/tests/unit/test_utils.py
podman/tests/utils.py

Fixes: https://github.com/containers/podman-py/issues/571

Skip tests conditionally based on version
