.cirrus.yml
bors.toml

See documentation https://bors.tech/documentation/getting-started/ and https://bors.tech/documentation/
Syntax 		Description
bors r+ 	Run the test suite and push to master if it passes. Short for “reviewed: looks good.”
bors merge 	Equivalent to bors r+.
bors r=[list] 	Same as r+, but the “reviewer” in the commit log will be recorded as the user(s) given as the argument.
bors merge=[list] 	Equivalent to bors r=[list]
bors r- 	Cancel an r+, r=, merge, or merge=
bors merge- 	Equivalent to bors r-
bors try 	Run the test suite without pushing to master.
bors try- 	Cancel a try
bors delegate+
bors d+ 	Allow the pull request author to r+ their changes.
bors delegate=[list]
bors d=[list] 	Allow the listed users to r+ this pull request’s changes.
bors ping 	Check if bors is up. If it is, it will …

Add bors for mergebot action

---

README.md

Fix link to contributing doc from README
Signed-off-by: Sagi Shnaidman <sshnaidm@redhat.com>

Fix link to contributing doc from README

---

podman/api_connection.py
podman/errors/__init__.py
podman/images/__init__.py
podman/networks/__init__.py
podman/system/__init__.py
podman/tests/unit/images/test_images.py
podman/tests/unit/networks/test_networks.py
podman/tests/unit/system/test_system.py
podman/tests/unit/test_api_connection.py
tox.ini

This change also includes a renaming of the api's static function to
raise a not found error to allow for alternative types of not found
exceptions to be raised (e.g. ImageNotFound, NetworkNotFound,
ContainerNotFound, etc)

Start networks implementation

---

Makefile

The change in #33 seems to have broken failures in unitests/linting from
stopping the check.

Revert Makefile tox usage

---

podman/__init__.py
podman/api_connection.py
podman/containers/__init__.py
podman/errors/__init__.py
podman/images/__init__.py
podman/networks/__init__.py
podman/system/__init__.py
podman/tests/unit/containers/test_containers.py
podman/tests/unit/images/test_images.py
podman/tests/unit/networks/test_networks.py
podman/tests/unit/system/test_system.py
podman/tests/unit/test_api_connection.py

* Reformat project with black formatter/style + isort
* Rename `__ALL__` to `__all__`
* Implement list_containers() + unit tests
Fixes #21 

Clean up code, list containers

---

CONTRIBUTING.md
podman/api_connection.py
podman/errors/__init__.py
podman/networks/__init__.py
podman/tests/unit/images/test_images.py
podman/tests/unit/networks/test_networks.py
podman/tests/unit/system/test_system.py
podman/tests/unit/test_api_connection.py
pyproject.toml
test-requirements.txt
tox.ini

This change documents the usage of black as the prefered formatter for
this project. Additionally it adds two tox targets that can be used to
have black be invoked.
* `tox -e black` will print out what would be changed
* `tox -e black-format` will actually update the files with the code
formatted
Black is configured via pyproject.toml with a line-length of 100 and
will skip string normalization
Closes #28
Signed-off-by: Alex Schultz <aschultz@redhat.com>

Use black formatter

---

podman/api_connection.py
podman/tests/unit/test_api_connection.py

* Change to libpod API 2.0.0
* Remove example code from coverage reports
* Add APIConnection ContextManager test

Bump API version and increase unittest coverage

---

README.md
podman/containers/__init__.py
podman/errors/__init__.py
podman/system/__init__.py
podman/tests/unit/containers/test_containers.py
podman/tests/unit/test_api_connection.py

This change picks up #20 and updates the containers start to use the
established api patterns.
Signed-off-by: Thierry Parmentelat <thierry.parmentelat@inria.fr>
Signed-off-by: Alex Schultz <aschultz@redhat.com>

Start containers module

---

contrib/cirrus/gating/Dockerfile

The integration tests being written as part of #48 leverage fixtures so
we need it installed when we run pylint or the job fails.  Additionally
this bumps the base container fedora to 33.

Add python3-fixtures and bump to fedora 33

---

podman/api_connection.py
podman/tests/unit/test_api_connection.py

In the api.request method, the error message returned by the server (for a request that generated an error 500, Internal Server Error) is not captured.
For example we might get:
podman.errors.InternalServerError: Request POST:/v2.0.0/libpod/containers/create failed: Server got itself in trouble
Instead of:
Decode(): json: cannot unmarshal string into Go struct field SpecGenerator.cni_networks of type []string
This makes troubleshooting issues in such requests difficult.
If the response body is in JSON and includes a "message" property, it is
extracted and included in the message of the exception raised.
closes issue #47
Signed-off-by: Nicolas Galler <ngl@odoo.com>

api_connection: extract message from server response

---

.cirrus.yml
Makefile
contrib/cirrus/gating/Dockerfile
podman/__init__.py
podman/api/__init__.py
podman/api/client.py
podman/api/parse_utils.py
podman/api/tar_utils.py
podman/api/url_utils.py
podman/api/version.py
podman/client.py
podman/config.py
podman/domain/images.py
podman/domain/images_build.py
podman/domain/images_manager.py
podman/domain/networks.py
podman/domain/networks_manager.py
podman/tests/errors.py
podman/tests/integration/base.py
podman/tests/integration/test_images.py
podman/tests/integration/test_networks.py
podman/tests/integration/test_system.py
podman/tests/integration/utils.py
podman/tests/unit/test_api_utils.py
podman/tests/unit/test_build.py
podman/tests/unit/test_config.py
podman/tests/unit/test_imagesmanager.py
podman/tests/unit/test_network.py
podman/tests/unit/test_networksmanager.py
setup.py

* Update Makefile with integration target
* Update client to support unix:// and http+unix:// schemes
* Add Images integration tests
* Refactor PodmanLauncher to log service output to log file to capture debugging events.
* Add option to allow podman service to log debugging events during integration test
* Refactor Image and ImagesManager as needed now integration tests running.
* Refactor unittests where as-built differs from swagger
Included from https://github.com/containers/podman-py/pull/48:
> This change adds a base integration class and a podman launcher that can
> be used to test the api calls and their expected results. Currently the
> podman calls that will work should be ones that can be performed as
> rootless. Eventually calls that require privilege (e.g. network) can be
> …

Flesh out Images integration testing 

---

podman/tests/integration/test_containers.py

The test uses memory in place of writing the tarball to disk. This
causes the check to fail. It is not clear why this test ever passed.

Remove tarfile.is_tarfile check in integration test

---

hack/get_ci_vm.sh

***WARNING***: DO NOT MERGE YET.  Core get_ci_vm container script not yet reviewed/finalized.
Depends on:
https://github.com/containers/automation_images/pull/57
https://github.com/containers/automation/pull/64
https://github.com/containers/automation/pull/66
https://github.com/containers/automation/pull/67
https://github.com/containers/automation/pull/68

Cirrus: Make use of shared get_ci_vm container

---

Makefile
README.md
podman/api/__init__.py
podman/api/client.py
podman/api/version.py
podman/domain/system.py
podman/tests/__init__.py
podman/tests/integration/test_containers.py
podman/tests/integration/test_system.py
podman/tests/unit/test_podmanclient.py
podman/tests/unit/test_system.py
setup.cfg

* Update demo in README.md
* Fix links in README.md
* Provide mapping for release version (podman.__version__) vs. API version
(api.VERSION)
* Fix /libpod/info endpoint tests
* Add upload and release targets to Makefile
* Build python3 wheel file for publication
* Port system integration tests to PodmanClient()

Updates for publishing to PyPi

---

podman/client.py
requirements.txt
setup.cfg

* Change urllib3 and pyxdg from ~= to >=, causing issues on fedora rpm
builds

Bump versions

---

docs/source/conf.py
podman/api/version.py
pyproject.toml
setup.cfg

* Add all dependencies to pyproject.toml
Changes re: https://bugzilla.redhat.com/show_bug.cgi?id=1956841#c13

Bump version for packaging changes

---

podman/domain/containers_create.py

Fix typos for 'portmapping', align types with documentation,
change way it's parsed.

Fix portmapping in container creation

---

podman/domain/containers.py

While developing against this API, I found the need to inspect a
container and gain an insight into its internals. It appeared that
inspect had not been implemented in podman-py, so I added it,
duplicating some code from the `container.kill()` function.
Signed-off-by: Eamonn Nugent <4699217+space55@users.noreply.github.com>

Add inspect capability to this container

---

.cirrus.yml
CODE-OF-CONDUCT.md
SECURITY.md
contrib/cirrus/latest_podman.sh

Ref: https://github.com/containers/common/issues/549

[CI:DOCS] Fix docs links due to branch rename

---

podman/domain/containers_create.py
podman/tests/integration/test_containers.py

* Corrected for field
* Added tests to ensure field is used correctly

Correct "ports" keyword for container create

---

podman/domain/containers.py

We can't post on that endpoint, it has to be a get.
```
Traceback (most recent call last):
File "clone_container.py", line 87, in <module>
main()
File "clone_container.py", line 80, in main
inspect = container.inspect()
File "/home/dvd/git/downstream/randoms/bin/.venv/lib/python3.7/site-packages/podman/domain/containers.py", line 225, in inspect
response.raise_for_status()
File "/home/dvd/git/downstream/randoms/bin/.venv/lib/python3.7/site-packages/podman/api/client.py", line 57, in raise_for_status
body = self.json()
File "/home/dvd/git/downstream/randoms/bin/.venv/lib/python3.7/site-packages/requests/models.py", line 900, in json
return complexjson.loads(self.text, **kwargs)
File "/home/dvd/git/downstream/randoms/bin/.venv/lib/python3.7/site-packages/simplejson/__init__.py", line 525, …
```

inspect should call a get not a post

---

.cirrus.yml
podman/tests/integration/test_containers.py

Prior-Ubuntu support is being dropped everywhere.
Ref: https://github.com/containers/podman/issues/11070
https://github.com/containers/automation_images/pull/88

Update VM Images + Drop prior-ubuntu references

---

podman/tests/integration/test_containers.py

In Podman 4.0, logs now return trailing newlines.
Needed to unblock PR queue

Update tests re: changes in containers.logs()

---

podman/__init__.py

Attempt to print meaningful error message if an older version Python
is used.

Assert Python version >= 3.6

---

podman/api/tar_utils.py

1. The pythonic way to do it is from the [PEP 8 style guide](https://www.python.org/dev/peps/pep-0008/):
For sequences, (strings, lists, tuples), use the fact that empty sequences are false:
```python
if not seq:
if seq:
if len(seq):
if not len(seq):
```
2. Use `[ ]` instead of `list()` (and its faster to initialize)

Check if list is empty in the pythonic way

---

podman/domain/containers_create.py
podman/tests/integration/test_container_create.py

According to documentation in podman-py there is a possibility to pass e.g. for memory limit `100m` which means 100 mega bytes of memory limit.
[Unfortunately there is no such possibility in REST podman API.](https://docs.podman.io/en/latest/_static/api.html#operation/ContainerCreateLibpod)
What is more you can pass in such a form (`100m`) from podman cli.
Which means we are lacking such functionality in podman-py (hence the PR).
Test code : 
```
import podman
client = podman.PodmanClient(base_url='unix:///run/podman/podman.sock')
options = [
{'kernel_memory': '20m'},
{'kernel_memory': 300},
{'mem_limit': 10000},
{'mem_limit': '256m'},
{'mem_reservation': 3000},
{'mem_reservation': '3000k'},
{'shm_size': …
```

Allow passing string values to memory limits

---

podman/api/tar_utils.py
podman/domain/images_build.py
podman/tests/unit/test_api_utils.py

The docstring for BuildMixin.build() specifies that the dockerfile
argument is relative to the path/build context.
BuildMixin.build() calls api.tar_utils.prepare_containerfile() whose
docstring specifies that the return value is relative to the context
directory.
This commit fixes a bug where the absolute path to the containerfile
was being returned from prepare_containerfile() causing the subsequent
image build to fail as the containerfile was not found at the erroneous
path.
This commit also fixes an incorrect test for the prepare_containerfile()
function.

Fix image build method to handle containerfile location correctly

---

podman/tests/integration/test_containers.py
podman/tests/unit/test_api_utils.py
podman/tests/unit/test_build.py
podman/tests/unit/test_container.py
podman/tests/unit/test_containersmanager.py
podman/tests/unit/test_imagesmanager.py
setup.cfg
test-requirements.txt
tox.ini

This PR adds support for Python 3.10. This required:
- Catering for the movement of Iterator and Iterable in the collections package in Python 3.10 (backwards compatibility with earlier Python versions is maintained)
- Migrating from Nose to PyTest for the test runner. Nose doesn't run under Python 3.10 and is unmaintained. PyTesthas really taken the community mindshare in recent years, and so this seems like a reasonable move. Two tests required modification for this. Those modifications were bug fixes.

Support Python 3.10

---

.cirrus.yml

Previously the VM images used for automation were
generic/one-size-fits-all.  However over time, various repos. have
required numerous updates resulting in a great deal of bloat.  To combat
this, a dedicated VM image has been crafted for use just by this repo.
Put this into use, and re-order tasks in `.cirrus.yml` to match more
closely with the order of operations.
Ref: https://github.com/containers/automation_images/pull/111

Cirrus: Use dedicated VM image for automation

---

podman/domain/containers_create.py
podman/tests/integration/test_container_create.py

It turned out I've forgotten to add `to_bytes()` to `memswap_limit` (which was done in #150).
So as a hotfix I've created another PR to fix it, along with test addition.
As a tradition, before the changes : 
```
4 failed, 161 passed, 3 skipped, 1 error in 90.22s
>>> import podman
>>> client = podman.PodmanClient(base_url='unix:///run/podman/podman.sock')
>>> container = client.containers.create(image='465a95569b4a', memswap_limit='1m')
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/lib/python3.6/site-packages/podman/domain/containers_create.py", line 225, in create
response.raise_for_status(not_found=ImageNotFound)
File "/usr/lib/python3.6/site-packages/podman/api/client.py", …
```

Add missing to_bytes for memswap_limit

---

podman/domain/containers.py

Logs' stream option is not working correctly right now. If it's set to `stream=True` and `follow=True` it does not return any logs from container.
Before my changes : 
```
>>> import podman
>>> import datetime
>>> client = podman.PodmanClient(base_url='unix:///run/podman/podman.sock')
>>> container = client.containers.create(image='465a95569b4a', entrypoint=['/bin/bash', '-c'], command=['sleep 2;echo 123;sleep 2;echo 456;sleep 2'])
print(f'[{datetime.datetime.now()}] {log}')>>> container.start()
>>> for log in container.logs(stream=True, follow=True):
...     print(f'[{datetime.datetime.now()}] {log}')
...
>>> container.remove()
>>>
```
and after changes : 
```
>>> import podman
>>> import datetime
>>> client …
```

Fix stream option for container logs

---

podman/domain/containers.py
podman/tests/integration/test_containers.py
podman/tests/unit/test_container.py

Use correct key when retrieving the resulting image after using
container commit to create said image.
* Update unittests to correct mocked results
* Add integration test for container commit()
Fixes #166

Fix container commit()

---

podman/domain/containers_create.py

As some networking options are no longer a thing, they were still in podman-py 4.0.
Definitely there are more of them but so far I've encountered these.
Those removed are in podman 3.4 but not in 4.0.
Option added is a new option in 4.0.
For reference please check : 
3.4 - https://docs.podman.io/en/latest/_static/api.html?version=v3.4#operation/ContainerCreateLibpod
latest - https://docs.podman.io/en/latest/_static/api.html#operation/ContainerCreateLibpod
After changes : 
```
>>> import podman
>>> client = podman.PodmanClient(base_url='unix:///run/podman/podman.sock')
>>> networks = {
...     "somenetwork": {
...          "aliases": ["test-alias"]
...     }
... }
>>> c1 = client.containers.create(name='test', …
```

Refactor network container options for podman 4.0

---

podman/domain/images_manager.py
podman/tests/integration/test_container_create.py
podman/tests/unit/test_imagesmanager.py

I've made this PR because it looks like that `tag` parameter was skipped when pushing image to registry.

Allow pushing images with tag different than latest

---

python-podman.spec.rpkg

Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>
@rhatdan @jwhonce PTAL . This fixes builds for rawhide, epel8 and epel9 koji envs, so I'm quite positive it will build successfully on our copr.

CoPR: Fix rpm builds for `rhcontainerbot/podman-next`

---

python-podman.spec.rpkg

Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>
c8s fails without this change: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/build/4537996/
c8s successful with this change: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/build/4538017/ 
@rhatdan @jwhonce PTAL.

CoPR: fix CentOS 8 Stream build

---

podman/domain/containers.py

https://docs.podman.io/en/latest/_static/api.html#operation/ContainerListLibpod returns the container labels in the `["Labels"]` attribute instead of `["Config"]["Labels"]`

containers.list() has a different labels attribute

---

podman/domain/containers_create.py
podman/tests/integration/test_container_create.py

Right now it is possible only to pass mode to mounted volume during container creation. I have no idea what was the reasoning behind it but the Podman REST API is capable of passing more options.
I'm only concerned about backward compatibility : 
- In docker-py option was called mode but there was possibility to pass multiple arguments (e.g. `z,ro`)
- I've renamed option `mode` -> `options` to be more precise what this option is actually doing so there is actually no backward compatibility with podman-py. Maybe this option should still be named `mode` and accept strings as well as list (?) - no idea whether it has to be backward compatible, if not, it is better to rename it.
```
>>> import podman
>>> client = …
```

Allow passing all available options to volume mount

---

podman/domain/containers.py

In non-stream mode, container.stats should work now
(fixing incorrect call of StringIO.writer instead of StringIO.write).

fix: Container.stats for non-stream mode

---

podman/domain/system.py
podman/tests/integration/test_system.py

use the compat auth endpoint to allow users to access login from within podman-py
resolves #189

podman-py login support

---

podman/domain/images_build.py

Corrected spelling of cachefrom to allow the kwarg through.
https://docs.docker.com/engine/api/v1.40/#tag/Image/operation/ImageBuild
Could not get all tests to pass, but the same failed before and after the change.
```
FAILED podman/tests/integration/test_adapters.py::AdapterIntegrationTest::test_ssh_ping - subprocess.TimeoutExpired: Command 'ssh -N -o StrictHostKeyChecking no -L /tmp/pyxdg-runtime-dir-fallback-pershey/podman/podman-forward-b42f7e8af6...
FAILED podman/tests/integration/test_container_create.py::ContainersIntegrationTest::test_container_devices - AssertionError: False is not true
FAILED podman/tests/integration/test_containers.py::ContainersIntegrationTest::test_container_crud - podman.errors.exceptions.APIError: 500 Server Error: Internal Server Error (can not pause …
```

fix issue #203

---

podman/domain/images_build.py

While working to replicate local podman image build commands in python, the 3 options, layers, output and outputformat were removed from kwargs in images.build.  These options are now passthrough to the REST API and replicated the caching that is done with the command line.  I extracted these options from the REST call made below and once added as pass-through, allowed caching to work.  Note, I am new to this so feedback would be great.  I could hardly find the output and outputformat options in any documentation except for buildah build under podman.
```
podman build -f /.../test_pdw_dockerfile.ubuntu2004 -t "pershey/test_pdw_dockerfile.ubuntu2004:latest"
```
Signed-off-by: Eric Pershey <pershey@anl.gov>

adding pass-through layers, output and outputformat to building images.

---

podman/api/http_utils.py
podman/tests/unit/test_api_utils.py

Adding support of passing empty strings in second level of dictionaries(environment variables, labels). 
This is needed for example during openstack deployment that uses empty passwords for monitor users inside databases and also for passing labels.
Signed-off-by: Ivan Halomi <i.halomi@partner.samsung.com>

Adding support of passing empty strings

---

Makefile
podman/tests/__init__.py
podman/version.py

Bump the podman-py version to 4.3.0 to be in lockstep with podman versions.

Bump version to 4.3.0

---

pyproject.toml
requirements.txt
setup.cfg

resolves https://github.com/advisories/GHSA-wqvq-5m8c-6g24
https://issues.redhat.com/browse/OCPBUGS-1926

update urllib to 1.26.5 for a CVE found in previous versions

---

.readthedocs.yaml

Correct path for rtd conf.py

---

.pylintrc
setup.cfg
tox.ini

* Removed configuration items from .pylintrc that are no longer supported and generating warnings.
* Locked "pylint" tox environment to python 3.10. Python 3.11 is not supported by Pylint 2.15.5. Dill dependency needs to be updated.

Clean up pylint configuration

---

podman/domain/config.py
pyproject.toml
python-podman.spec.rpkg
requirements.txt
setup.cfg

Replace the unmaintained `toml`/`pytoml` dependencies with the modern alternatives: the built-in `tomllib` module in Python 3.11, and `tomli` in older Python versions.  Preserving backwards compatibility does not seem necessary, as podman-py no longer supports Python versions older than 3.6.
Signed-off-by: Michał Górny <mgorny@gentoo.org>

Use modern tomllib/tomli modules for reading TOML files

---

podman/domain/containers_create.py
podman/tests/integration/test_container_create.py

Added support for `range` in `ports`.
The range is available at REST API but was not supported in podman-py.
I've tried to keep the backward compatibility (hopefully it works, previously written test case works at the very least).
Unfortunately it was impossible to add `range` without adding new syntax for ports (using dictionary instead of None or int or tuple or list).
The newly added syntax should work in the same manner as the previously used one, but with addition of `range` keyword.

Added port binding range

---

podman/domain/containers.py
podman/domain/containers_create.py
podman/domain/containers_manager.py
podman/domain/containers_run.py
podman/tests/unit/test_containersmanager.py

This set of changes fixes the broken `.run()` capability, and adds some docstrings and clarifications along the way.
This fixes #201 and item 3 in #184.

Fix the ability to run containers

---

Makefile
podman/tests/__init__.py
podman/version.py

Bump the podman-py version to 4.4.0 to be in lockstep with podman versions.

Bump version to 4.4.0

---

podman/domain/config.py
pyproject.toml
python-podman.spec.rpkg
requirements.txt
setup.cfg

This reverts commit c5a356fb4ea8a6fb66a6d20bdc2c9cffe615028b.
Reverting as there is packaging issues with the new toml library that was being added.

Revert "Use modern tomllib/tomli modules for reading TOML files"

---

podman/domain/config.py
pyproject.toml
python-podman.spec.rpkg
requirements.txt
setup.cfg

This reverts commit c5a356fb4ea8a6fb66a6d20bdc2c9cffe615028b.

[v4.4-rhel] Revert "Use modern tomllib/tomli modules for reading TOML files"

---

podman/domain/containers.py

Fixes #218 
The current behavior of the `Container.stats` method does not take into account the streaming mode, leading to it freezing when we use it in stream mode. It also has other issues regarding decoding even when its being used in a non-stream mode. This PR fixes those issues.
I've also updated some type-hints, which I think are wrongly typed.
Feel free to request changes if you think they are inappropriate.

Fix Container.stats behaviour

---

setup.cfg

This restores compatibility with older setuptools versions.
NB, the version needs to be kept in sync between setup.cfg and version.py.
Relates: https://github.com/containers/podman-py/pull/244

Specify version verbatim in setup.cfg

---

podman/api/__init__.py
podman/api/parse_utils.py
podman/domain/containers.py
podman/tests/unit/test_container.py
podman/tests/unit/test_parse_utils.py

Changes:
- Add a common `stream_helper` to stream and decode json responses
- Switches existing methods to use the newer helper.
- Fixes Container.top issues mentioned in #249 
The `stream_helper` would be useful when other APIs require streaming and JSON decoding like for the API mentioned  in #239
Please do let me know in case something needs to be changed or amended.
Closes #249

Fix stream issues in container.top

---

podman/domain/containers_create.py
pyproject.toml

Rather than duplicating the podman documentation use an URL to point the legal values for userns and uts
[NO NEW TESTS NEEDED]
Fixes #260

Change docstring to point to podman docs

---

podman/domain/pods_manager.py
podman/tests/unit/test_podsmanager.py

Podman API supports streaming Pod stats, but podman-py does not support that as of now.
This PR aims to add support for that.

Streaming support for PodsManager.stats API

---

podman/tests/integration/test_containers.py
requirements.txt
setup.cfg

Revert "chore(deps): update dependency urllib3 to v2"
This reverts commit 6d37fea009233246d513c95041e8c67e4265f834.

[v4.5-rhel] cherry-pick urlib3 fixes

---

podman/domain/containers_manager.py

Hi!
When `containers.prune()` is called, it currently fails silently since it looks for errors under the wrong key. The API returns it under the `Err` key and not the `error` key.
Tested using podman `4.5.1`.
Thank you!

Fix catching errors in the response body of containers/prune

---

Makefile

* Assumes homebrew is installed and configured
* Uses which in place of command -v which is not implimented on MacOS
* Assumes if dnf is not found use brew. aptget support could be added in future
Note: Testing machine had run xcode-select --install

Refactor Makefile to support tox / MacOS Ventura

---

Makefile
podman/tests/__init__.py
podman/version.py
rpm/python-podman.spec
setup.cfg

Use `-dev` to denote development branch.
`LIBPOD_URL` in `poodman/tests/__init__.py` doesn't work with `-dev`, so
we only use `vX.Y.Z`.

Keep main branch version ahead of release branches

---

podman/domain/images_manager.py
podman/tests/integration/test_images.py
podman/tests/unit/test_imagesmanager.py

From Podman 4.0, the endpoint for image search ([doc](https://docs.podman.io/en/latest/_static/api.html?version=v4.0#tag/images/operation/ImageSearchLibpod) ) includes the possibility to include a `listTags` (bool) parameter that allows the user get all the available tags for a specific image in the registry.
Similar suggestion (and solution) was raised in [Issue 264](https://github.com/containers/podman-py/issues/264).
The parameter is only included in the API request if the user includes it in the kwargs parameters for the function, so this change should not break anything if the user is interacting with some podman instance < 4.0.
Unit and integration tests have been included in the PR.
Signed-off-by: apozsuse <andres.munoz@suse.com>

Includes the possibility to use the 'listTags' parameter in image search endpoint

---

test-requirements.txt

To ensure compatibility on py3.6 as well.

Update fixtures to not be tied to a version

---

.packit.yaml

The Fedora package name doesn't match upstream name. As a result, packit cannot automatically detect the right package repo for downstream tasks unless downstream_package_name is specified.
Success can only be verified in the next upstream release.
Ref: https://packit.dev/docs/configuration#downstream_package_name

Packit: mention `downstream_package_name: python-podman` in config

---

podman/domain/networks_manager.py

This direct logging to sys.stderr seems to happen only on this line. There is nowhere else in the code that does this.

remove direct logging to sys.stderr

---

podman/domain/containers_create.py

1. Minor fix
Minor typo fix out of context: "example :" to "example:"
2. Secrets
The previous implementation of the secrets parameter allowed a string or Secret object to be defined.
The parameter passed to the API resulted in {"ID":str}.
While testing the secrets API I found that having only a single secret defined worked fine while more than one secret resulted in an exception:
```
500 Server Error: Internal Server Error (more than one result secret with prefix : secret is ambiguous)
```
The parameter ID was never used and a prefix of "" (empty) assumed.
Having a single entry in the Secrets Manager will always result in a single result, no matter the filter.
After losing myself in the API documentation, the correct data format I found is the following:
```
{
"source": "my_secret", # …
```

Fixes the secrets parameter, adds the secret_env parameter

---

podman/domain/images_manager.py

Due to a logic error when trying to use the image scp functionality the destination wasn't passed unless "quiet" was also set.

Fix image SCP when not providing quiet

---

podman/domain/containers.py

Closes #323
According to the documentation comment below, this value should be set to False. Furthermore, this is the behavior of docker-py, so it will be expected by many users. Therefore I think it should be `False` by default.

Change default value for tty in exec_run

---

.readthedocs.yaml
podman/domain/containers_create.py
podman/domain/images_manager.py
podman/domain/ipam.py
podman/tests/integration/test_container_create.py
podman/tests/integration/utils.py
podman/tlsconfig.py

Builds on readthedocs was failing due to a new requirement in the yaml. Fix that to get the builds working again.

Fix readthedocs yaml

---

podman/domain/images_manager.py
test-requirements.txt

Add a new arg option called progress_bar that when set to true will display a progress bar with the image pull progress. This uses the compat endpoint as that is the data we are able to parse to displat the progress bar.

Add progress_bar option to image pull

---

podman/domain/images_manager.py
requirements.txt
rpm/python-podman.spec
setup.cfg
test-requirements.txt

This allows the 'rich' dependency, which has additional dependencies and is not available in RHEL, to be optional.
Fixes: #360

Make progress_bar an extra feature

---

podman/domain/containers_create.py

Allow user to specify netns => Example {"network_mode": "ns:/var/run/netns/<NETNS>"}

Enable user defined netns

---

podman/api/client.py

The `max_pool_size` was typed `max_pools_size`  in the `APIClient` class and it caused issue.
**Test code:**
```python
import podman
import requests
client = podman.from_env()
```
**Output:**
```text
>>> python3 test.py
Traceback (most recent call last):
File "/local/user/podman_test/tools/test.py", line 11, in <module>
client = podman.from_env()
File "/local/user/podman_test/venv/lib/python3.9/site-packages/podman/client.py", line 131, in from_env
return PodmanClient(
File "/local/user/podman_test/venv/lib/python3.9/site-packages/podman/client.py", line 77, in __init__
self.api = APIClient(**api_kwargs)
File "/local/user/podman_test/venv/lib/python3.9/site-packages/podman/api/client.py", line 136, in __init__
self.mount("http://", HTTPAdapter(**adapter_kwargs))
TypeError: __init__() got …
```

Fix the 'max_pool_size' parameter passing for Adapters

---

podman/domain/containers_create.py

Currently `podman-py` uses all three versions of `work_dir`, `working_dir` and `workdir` (not to mention `WorkingDir`).
This commit tries to unify the parameter usage by allowing `workdir` for container `create` or `run`. For backwards compatibility `working_dir` still works.
Since upstream Podman uses a variety of *workdir* versions the `podman-py` codebase can't be simplified further.
Fix: #330

Add `workdir` as alias for `working_dir`

---

podman/api/client.py

Completely remove the depcrecated max_pools_size
arg.

Remove deprecated max_pools_size arg

---

podman/domain/containers_create.py

The Podman API clarifies the field to give is `dns_option`, not `dns_options` [here](https://docs.podman.io/en/stable/_static/api.html?version=v4.5#tag/containers/operation/ContainerCreateLibpod), so we need to drop the `s` to allow `dns_opt` fields to properly populate.
I thought about writing more unit tests for `containers_create.py` but there weren't existing tests for any of the options yet, so we'll have to add them for each API option I'd think.
Test program:
```python
import json
from podman import PodmanClient
uri='unix:///run/user/1000/podman/podman.sock'
with PodmanClient(base_url=uri) as client:
container = client.containers.create(
image='registry.access.redhat.com/ubi8',
command=['sleep 500'],
dns_opt=['edns0'],
)
```
Now properly works since we're passing in the right name: …

Fix dns_option typo

---

podman/api/http_utils.py

For authentication for push/pull operations over registries, the value the `X-Registry-Auth` HTTP header is the base64 encoded of the json dump of the authorization data.
Plain base64 encoding causes problems if `+` character is present in the base64 encoded value, as `+` is a special separator in HTTP headers. The request is rejected by registries if '+' is present in that base64 encoded data.
It's required to change the plain base64 encoding for `url_safe` base64 encoding, as this encoding avoid using the problematic characters for HTTP and that's the encoding the registries  are expecting.
The base64 `url_safe` encoding is present already in [podman client](https://github.com/containers/podman/blob/5c39ddca5dc7ac026ba4eacfd271450e7d0c7008/pkg/auth/auth.go#L213) or …

Fixes encoding of `X-Registry-auth` HTTP Header value from Base64 to `url_safe` Base64

---

podman/api/client.py

ignore proxies from the env vars when using UNIX Domain Sockets

---

podman/domain/config.py

Description is trivial: `old_toml_file` is undefined in the else block.

Fix Pylint E0606 for undefined variable after else

---

README.md

Fix README TypeError when one container is running

---

.cirrus.yml

With Renovate managing CI VM updates, when a major Fedora release happens, additional manual work is required to update the CI task names so they match the release number.  This is extra burdensome on maintainers, stop it.
Example Ref: https://github.com/containers/podman-py/pull/389

Remove Fedora release number from task names

---

podman/api/path_utils.py
podman/api/ssh.py
podman/client.py
podman/domain/config.py
podman/tests/unit/test_podmanclient.py
requirements.txt
setup.cfg
tox.ini

related to https://github.com/containers/podman-py/issues/397

Add python 3.12 support and remove python xdg

---

docs/source/index.rst

I believe the example to be incorrect as it stands. The class invoked should be `PodmanClient`

Update index.rst Client -> PodmanClient

---

podman/domain/images.py
podman/tests/integration/test_images.py

In the Image.save method, the `named` argument was ignored. The `self.id` argument was always used, resulting in an empty `repositories` file in the tarball. As a result, if the tarball was loaded into `Podman`, the image was not given a name (only `None`). This limitation can cause problems in some cases, since the name of the imported image is not known.
**The used minimal script:**
```python
import podman
with podman.PodmanClient() as client:
with open("hello_image.tgz", "wb") as file:
image = client.images.get("hello:latest")
for chunk in image.save(named=True):
file.write(chunk)
```
**Before my change:**
```bash
>>> tar -xvf hello_image.tgz
c13e6cd75347b97d0c518979dfa54033e6582b8915fc222c44491438f5c33791.tar
633eb872fc662b2f070514927075745206904c96442aace19754cdab171dc4c7.json …
```

Implementing the functionality of the 'named' argument of the 'Image.save' method

---

podman/client.py
podman/domain/containers_manager.py
podman/domain/containers_run.py
podman/domain/images_manager.py
podman/domain/manager.py

The code for running a new container with an image that is not present locally tries to access the `ImagesManager` via `self.client.images`.
As `self.client` is an `APIClient` instance and not an instance of `PodmanClient`, an `AttributeError` occurs:
```python
AttributeError: 'APIClient' object has no attribute 'images'
```
With this fix the `PodmanClient` object is used instead of `APIClinet` correctly.
**A very minimal test code:**
```python
import podman
with podman.PodmanClient() as client:
client.containers.run("docker.io/library/busybox:latest")
```
The above code failed with `AttributeError` before my fix. Currently it pulls the Image if it's not available in local and run the container.
**Note:**
-  I guess the other `@cached_property` methods also can be extended with my …

Fix the locally non-existent image fails with AttributeError

---

podman/api/output_utils.py
podman/domain/containers.py
podman/tests/integration/test_container_exec.py

`exec_run` now returns a tuple of bytes if demux is True the first element being the stdout and the second the stderr of the exec_run call.
Implementation is courtesy of:
https://github.com/SatelliteQE/broker/blob/60a52941f2eb297ccbdf7a0fa0b932eb23ad926b/broker/binds/containers.py#L8-L48
Resolves: https://github.com/containers/podman-py/issues/322
Thanks @JacobCallahan

Enable demux option in `exec_run`

---

Makefile
podman/tests/__init__.py
podman/version.py
setup.cfg

Bump version to 5.1.0

---

podman/domain/images_manager.py
podman/tests/unit/test_imagesmanager.py

If the prune doesn't remove images, the API returns `null` (with `200` status code) and it's interpreted as `None` (`NoneType`) so the for loop throws the following exception:
```
"TypeError: 'NoneType' object is not iterable".
```
My fix handles the above described case and the `client.images.prune()` returns a valid Dict with zero values, which is correct because the Podman didn't remove anything:
```python
{
"ImagesDeleted": [],
"SpaceReclaimed": 0,
}
```
**It's fix for:**
- https://github.com/containers/podman-py/issues/275

Fix the TypeError exception in the images.prune method

---

.packit.yaml

When the fedora package name doesn't match with the upstream repo, the `downstream_package_name` key needs to be mentioned for each package config (fedora, centos).

[skip-ci] Packit: downstream_package_name for each package key

---

podman/tests/integration/test_container_create.py

This PR adds a test of container creation with the DNS option.  The test covers #386.

Add test of container create with  DNS option

---

.cirrus.yml
Makefile
podman/tests/integration/test_images.py

Podman search is an infrequently used feature, that tends to flake a lot. Also stop linting twice, and update CI VM images.
Example failure log: https://cirrus-ci.com/task/4801063868432384

Fix podman search flake + update CI VM images

---

podman/domain/ipam.py
podman/domain/networks_manager.py

When user specifies a IPAM driver through IPAMConfig, the driver value was ignored and not translated to json used in network create command. This patch fixes the issue by translating the IPAM driver configuration in network_create json data.
Code to create network:
```
from podman import PodmanClient
from podman.domain.ipam import IPAMConfig
podman_client = PodmanClient(base_url="unix:///run/podman/podman.sock", timeout=60)
ipam_config = IPAMConfig(
driver="none",
)
podman_client.networks.create(
"lnst_container_net_net1",
internal=True,
enable_ipv6=True,
ipam=ipam_config,
)
```
Before change 
```
[
{
"name": "lnst_container_net_net1",
"id": "b3a290de4cfe29d4a06655689c02a8979ecf7a5c104f387b06f5dbc4b38abfb6",
"driver": "bridge",
"network_interface": "podman1",
"created": …
```

domain/networks_manager.py: use specified driver in IPAMConfig

---

podman/api/client.py
podman/api/ssh.py
podman/api/uds.py
podman/client.py
podman/domain/containers.py
podman/domain/containers_run.py
podman/domain/system.py
podman/errors/exceptions.py

Two ways of fixing this:
- Ignore R0917 for internal functions such as __int__
- Fix the positional arguments with *
Testing against Pylint stable.
Source of Pylint 3.3.1 docs
https://pylint.readthedocs.io/en/stable/user_guide/messages/refactor/too-many-positional-arguments.html

Fix/Disable Pylint R0917

---

podman/api/client.py
podman/domain/images_manager.py
podman/domain/system.py
podman/tests/unit/test_imagesmanager.py

The new parameters of login method based on [SystemAuth docs](https://docs.podman.io/en/latest/_static/api.html#tag/system-(compat)/operation/SystemAuth):
- **auth**: TBD description
- **identitytoken**: IdentityToken is used to authenticate the user and get an access token for the registry.
- **registrytoken**: RegistryToken is a bearer token to be sent to a registry
- **tls_verify**: Whether to verify TLS certificates.
The new parameter of images.load method:
- file_path: Path of the Tarball. If it's set then the load method opens the file and reads it as bytes. It means the method is able to handle file path as well, not only bytes. The scenarios when none of parameters or both of them are set are handled in the method.
**Fix for:**
- https://github.com/containers/podman-py/issues/419

Extend the parameters of 'images.load' and 'login' methods

---

podman/domain/containers.py

Instead use whatever user the container uses per default, which might be `root` but may also be something else. This avoids manually figuring out the default user in case some files inside the container are specifically owned by a non-root user.

Don't use `root` as default user for exec_run

---

.github/renovate.json5

@inknos PTAL.  Happy to change this to somebody(s) else if desired or remove the default assignment entirely.

Renovate: Update default assignment

---

.packit.yaml

rpmautospec is now enabled on c9s envs so we should be ok to use the spec file maintained upstream for c9s as well.
Fixes: RUN-2123
@inknos PTAL

Packit: enable c9s downstream update

---

podman/domain/containers_run.py

Currently if the `detach=True` and `remove=True` parameters are specified in  the same command, the container is not deleted.
**Reproduce the issue:**
```python
from podman import PodmanClient
uri = "unix:///run/user/1000/podman/podman.sock"
with PodmanClient(base_url=uri) as client:
c = client.containers.run("nginx", deatch=True, remove=True, command="/bin/false")
print(c.status)
```
With this change if the above parameters are provided then the container object is returned and the container removing (wait method is included) is started on a separated thread.
**Fix for:**
- https://github.com/containers/podman-py/issues/402

Remove the container in case of detach mode

---

.packit.yaml

This helps to avoid dup packit jobs during downstream updates.

Packit: constrain koji and bodhi jobs to fedora package

---

podman/domain/containers.py

Fixes issue I reported in https://github.com/containers/podman-py/issues/451
> The docstring for container.logs states that the default value of the stderr keyword arg is True, when in fact if you look at the function code it defaults to None which is treated as False

Fix default stderr value of container.logs() to match documentation.

---

podman/domain/containers_create.py
podman/tests/integration/test_container_create.py
podman/tests/integration/test_containers.py
podman/tests/unit/test_containersmanager.py

Currently in containers_create.create(), the ports dict parameter is described as
> The keys of the dictionary are the ports to bind inside the container, either as an integer or a string in the form port/protocol
however, if the dict passed as this parameter has an integer as a key, it will result in a TypeError from the code on L625 `if "/" in container`.
Fix this by casting any integer keys to be strings beforehand.

Accept integer ports in containers_create.create

---

podman/domain/containers_create.py
podman/tests/integration/test_container_create.py

Fixes https://github.com/containers/podman-py/issues/151
The `volume` parameter when creating containers seems to be common cause of confusion and frustration when migrating from dockerpy to podmanpy. The docker API supports mounting directories through said parameter whereas podman wants users to use the `mounts` parameter despite what the documentation claims:
https://github.com/containers/podman-py/blob/7a674914edb15b2c3e657e74f0eca778a66eb9bc/podman/domain/containers_create.py#L304-L331
Currently, if a user tries to use the `volumes` keyword for directories they will get the following error:
`podman.errors.exceptions.APIError: 500 Server Error: Internal Server Error (error creating named volume "/home/user1/": error running volume create option: names must match …

Added support for mounting directories through the volume keyword.

---

docs/source/index.rst
podman/domain/images_manager.py
podman/tests/unit/test_imagesmanager.py

fix: name filter in images.list()

---

podman/api/path_utils.py
podman/tests/unit/test_path_utils.py

XDG mentions `/run/user/$UID` as the value for `XDG_RUNTIME_DIR`:
* https://www.freedesktop.org/software/systemd/man/latest/pam_systemd.html
* https://serverfault.com/questions/388840/good-default-for-xdg-runtime-dir/727994#727994
Archlinux, Debian, RedHat, Ubuntu, etc all use `/run/user/$UID` because they follow XDG:
* https://wiki.archlinux.org/title/XDG_Base_Directory
I found this while using podman-py on a minimal headless Debian server setup, where  `/run/user/$UID` was in use  but `XDG_RUNTIME_DIR` was not set.  The existing fallback in `/tmp` did not work.

/run/user/$UID as fallback if XDG_RUNTIME_DIR is not set

---

podman/api/path_utils.py
podman/tests/unit/test_path_utils.py

I got one key detail wrong in #475: `/run/user` is based on UID not username. This fixes that and is better tested.

fix: /run/user/ is based on UID not username

---

podman/domain/images_manager.py
podman/tests/unit/test_imagesmanager.py

Param all is now supported by prune.
Param external is now supported by prune.
Filter by label, which was already supported, is now documented and tested.
Resolves: https://github.com/containers/podman-py/issues/312

Add all, external, and label to Image.prune()

---

.cirrus.yml
contrib/cirrus/build_podman.sh

build from https://github.com/containers/automation_images/pull/396
---
cirrus: replace dnf command
The new images updated to f41 and thus contain dnf5, dnf erase is no
longer valid so just call dnf remove to remove the package.

New CI Images

---

podman/domain/containers_create.py
podman/tests/integration/test_container_create.py

Fix https://github.com/containers/podman-py/issues/486

Support uppercase mount attributes

---

podman/domain/images_manager.py
podman/domain/json_stream.py
podman/errors/__init__.py
podman/errors/exceptions.py
podman/tests/integration/test_images.py

Implement `decode (bool)` parameter in `pull()`. Decode the JSON data from the server into dicts. Only applies with `stream=True`.
If `decode` is not implemented, the output will be something like:
```
b'{"stream":"Trying to pull docker.io/ohmyzsh/zsh:latest...\\n"}
...
```
By implementing `decode` the pull output will be:
```
{'stream': 'Trying to pull docker.io/ohmyzsh/zsh:latest...\n'}
```
It partial covers https://github.com/containers/podman-py/issues/456

Implement "decode" parameter in pull()

---

podman/domain/containers.py
podman/tests/integration/test_containers.py
podman/tests/unit/test_container.py

In reference to my issue #490, I have drafted a patch to add support for the operation.
I have performed some trivial manual testing of the change, but trying to run `tox` results in the log line below repeating indefinitely, and as such I have not run the various testing facilities that the project provides.
If anyone would be able to help me to get the tests running, I would be more than happy to also contribute additional coverage for this new method.
```
------------------------------------------------------------------------------- live log call --------------------------------------------------------------------------------
2025-01-05 18:10:08 [    INFO] Launching(5.3.1) podman --log-level=info system service --time=0 unix:///tmp/tmpqcq78j4c/ad527583baab4ebb96975b65cda25702 …
```

Add support for container initialization

---

podman/domain/containers_create.py

This makes its interface consistent with its own documentation, and with Container.run, by allowing both a list of arguments and a single string for the `command` parameter.

fix: accept a string for the `command` argument of Container.start

---

podman/domain/containers_create.py
podman/domain/containers_run.py

This addresses the issue described in detail in #496, by updating the docstring for the `create()` and `run()` operations of Container.

Clarify documentation of container removal flags

---

podman/domain/images_manager.py

Sorry @rhatdan This PR replaces https://github.com/containers/podman-py/pull/495 due to some conflicts and need of rebase. For simplicity I opened this one in a clean manner.
Fix https://github.com/containers/podman-py/issues/492
Added `compatMode` param to `pull()` function. Default as `True` in order to give a detailed progress JSON output by default like:
```
...
{'status': 'Pulling fs layer', 'progressDetail': {}, 'id': 'ef3afbc03436'}
{'status': 'Downloading', 'progressDetail': {'current': 1862903, 'total': 37308955}, 'progress': '[==>                                                ]  1.863MB/37.31MB', 'id': '1546de61b6c3'}
{'status': 'Download complete', 'progressDetail': {}, 'id': 'fa424c11eb04'}
{'status': 'Pulling fs layer', 'progressDetail': {}, 'id': '3d3d38ab8766'}
{'status': …
```

Add compatMode raw JSON output and fix tls_verify init on pull()

---

podman/domain/networks.py

This and other methods don't pass **kwargs to requests
and therefore it is not possible to enable the compatible
endpoint.

Add **kwargs to Network.connect call

---

pyproject.toml
setup.cfg

The podman pyproject.toml was updated to fix a packaging issue that prevented the `import podman.api` to work.
This caused an issue in the package versioning. Python-podman cannot be bumped to version 5.4.1 since it will try to use the libpod/v5.4.1/ endpoint which is not released yet. Python-podman uses the same versioning scheme and so the package need to add a fourth digi in the version scheme to be released on PyPI. This can be avoided in distribution packages with the option of a new release or a patch downstream, but on GitHub and PyPI this is the workaround.
Source for packaging Python software
https://packaging.python.org/en/latest/specifications/version-specifiers/#version-specifiers

Bump release to 5.4.0.1

---

podman/domain/images_manager.py

IMO this was an oversight at:
- #434 
The PR (#434) changed the return type from `Generator[Image, None, None]` to `Generator[bytes, None, None]`
The generator was created with the return value from `get`. `get` returns an `Image`
https://github.com/containers/podman-py/blob/2a29132efab4a183580a30d9c18b9bdb61b5ab49/podman/domain/images_manager.py#L162-L168
https://github.com/containers/podman-py/blob/2a29132efab4a183580a30d9c18b9bdb61b5ab49/podman/domain/images_manager.py#L83

fix: set return type for `ImagesManager.load()` to `Image`

---

podman/tests/integration/test_images.py

Debian and other distros still ship for 32-bit systems.  But some of the test images are not available for 32-bit archs:
* https://ci.debian.net/packages/p/python-podman/testing/armel/58665732/
* https://ci.debian.net/packages/p/python-podman/testing/armhf/58665757/
* https://ci.debian.net/packages/p/python-podman/testing/i386/58561143/

skip tests when the test image is not available (e.g. 32-bit)

---

podman/domain/containers_create.py
podman/tests/unit/test_containersmanager.py

`cgroupns`, `ipcns`, `pidns`, `userns`, `utsns` now support setting the `value` attribute.
This allows to mimic the behavior of `--userns`[0] cli arg via this API.
[0]: https://docs.podman.io/en/stable/markdown/podman-create.1.html#userns-mode
Maybe related to #499
---
We spotted this missing behavior when using `salt-podman-formula`, we realized that setting:
```yaml
container:
userns_mode:
nsmode: keep-id
value: "uid=1000"
```
Was not bringing the `.container.userns_mode.value` to the actual invocation. The patch allows consumers to send a dict with the options, there's potential to do string parsing (to mimic 1:1 the parsing that the cli does) if desired.

feat: expose `*ns` keys to consumers

---

podman/api/__init__.py
podman/api/http_utils.py
podman/domain/images_manager.py
podman/domain/manifests.py
podman/tests/unit/test_api_utils.py
podman/tests/unit/test_imagesmanager.py
podman/tests/unit/test_manifests.py

- Allows the setting of an authentication header similar to the push of images (related to #164)
- The current api to push manifests has been deprecated since podman 4.0 ([`http://podman.io/libpod/manifests/{name}/push`](https://docs.podman.io/en/latest/_static/api.html#tag/manifests/operation/ManifestPushV3Libpod))
- Use the "new" API: [`http://podman.io/libpod/manifests/{name}/registry/{destination}`](https://docs.podman.io/en/latest/_static/api.html#tag/manifests/operation/ManifestPushLibpod)
I was already unable to use the old API with Podman 4.9
The current implementation for image push:
https://github.com/containers/podman-py/blob/a75e8c2b848d4f48af6f72c3170b5aa02bdff092/podman/domain/images_manager.py#L241-L268

Set X-Registry-Auth header on manifest push and bump to new API

---

.github/workflows/publish-to-test-pypi.yml

Sometimes push to Test PyPI fails with 404. It is necessary to add verbose to see what's happening.
Some examples:
https://github.com/containers/podman-py/actions/runs/13407882925/job/37451651001
https://github.com/containers/podman-py/actions/runs/13494294813/job/37698067450

Set verbose: true to debug twine uploads to PypI

---

Makefile
plans/main.fmf
podman/tests/__init__.py
podman/version.py
setup.cfg

This PR should enable testing on updates-latest, so we can test on 5.5.0 binaries before they get stable karma

Bump release to 5.5.0 and enable updates-testing repos on Fedora

---

.readthedocs.yaml

Part of:
- #532 
Follow up to:
- #546 
Docs and example: https://docs.readthedocs.com/platform/stable/config-file/v2.html#packages
Current failure: https://app.readthedocs.org/projects/podman-py/builds/28555767/
```
Config file validation error Config validation error in python.install. Expected a list, got type dict ({'path': '.', 'method': 'pip', 'extra_requirements': ['docs']}).
```

fix: broken configuration for readthedocs

---

podman/domain/networks.py

The `id` and `containers` attrs should be lowercase.
Fixes #527

Fix attr getters in Network Resource

---

.github/actions/build-python-package/action.yml
.github/workflows/build.yml
.github/workflows/publish-to-pypi.yml
.github/workflows/publish-to-test-pypi.yml

The step to create GH release is clunky, confusing, and fails most of the time. The code was supposed to be triggered on a new tag, but it's simpler to create a release from the GH dashboard and let it create the tag as well, which triggers pypi.
In the first commit, the workflow mirrors the one from packaging.python.org page but with few differences:
"if" condition in publish-to-test-pypi, to run on main branch only
skip-existing test.pypi releases is true to try and reduce the pypi usage
https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#the-whole-ci-cd-workflow
---
In the second commit, the build steps are split in an action and three separate workflows that should
- build on every PR (and don't upload artifacts …

Inknos update publish to pypy steps
